name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            file: rust_guessing_game
          - os: windows-latest
            file: rust_guessing_game.exe


    runs-on: ${{ matrix.platform.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: guessinggame-${{ matrix.platform.os }}
        path: target/debug/${{ matrix.platform.file }}